#!/bin/bash

declare regex='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'

function regular () {
declare site=`basename $(dirname $(dirname $1))`
declare user=`basename $(dirname $1)`
declare repo=`basename $1 .git`
echo -e "Original link: $1\n\nResulting link: git@$site:$user/$repo.git"
}

function silent () {
declare site=`basename $(dirname $(dirname $1))`
declare user=`basename $(dirname $1)`
declare repo=`basename $1 .git`
echo git@$site:$user/$repo.git
}

function help () {
echo -e "https-into-ssh [<arg>] <repo> \nThis is help note for this script. \nInputted args:\n\t--help or -h: show this page.\n\t--silent or -s: shows only resulting link."
}

function selection () {
if [ "$1" == "--help" -o "$1" == "-h" ]
then
	help
elif [ "$1" == "--silent" -o "$1" == "-s" ]
then
	if [[ $2 =~ $regex ]]
    then
        silent $2
    else
        echo "Wrong repo. Please check repo or run script with \"-h\" or \"--help\" to see help page."
    fi
elif [[ $1 =~ $regex ]]
then
	regular $1
else
	echo "Wrong arg. Please run script with \"-h\" or \"--help\" to see help page."
fi
}

function input () {
if [ -n "$1" ]
then
	selection "$@"
else
	help
fi
}

function main () {
input "$@"
}

main "$@"